Attach sources when deploying or preparing a release
struts-community-plugins/struts2-jquery pull request #574
Opened 2024-11-20 06:41 UTC by lukaszlenart

**NOTE**: this fix didn't help (at least when testing locally)

Each time I'm trying to prepare a new release I must manually create and deploy source by checking out a tag and then running `mvn source:jar deploy -Prelease` again.

Even with this fix, running `mvn deploy` doesn't produce a jar file with source code locally.

Any help? cc: @sepe81 @sdutry

2024-11-20 21:23 UTC, sepe81 commented
@lukaszlenart Do you use the maven-release-plugin via [mvn release:perform](https://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html#release-perform) for releases? If so, could you share the exact command you use?

Instead of using `<arguments>-Prelease ${arguments}</arguments>`, you might consider `<releaseProfiles>release</releaseProfiles>`, which [appears to be more explicit](https://maven.apache.org/maven-release/maven-release-plugin/perform-mojo.html#releaseprofiles).

Perhaps using `<dryRun>true</dryRun>` could also be helpful for debugging?

2024-11-20 21:29 UTC, sepe81 requested changes

2024-11-20 21:29 UTC, sepe81 commented on pom.xml
> +							<phase>verify</phase>
```suggestion
```

The default is `package`, which should be sufficient.

see https://maven.apache.org/plugins/maven-source-plugin/jar-no-fork-mojo.html

2024-11-20 21:49 UTC, sepe81 commented
I adjusted the plugin order locally and observed that source:3.3.1:jar-no-fork now runs before deploy. Hopefully, this resolves the issue. The plugin execution order in Maven can be tricky at times.

[INFO] --- javadoc:3.11.1:jar (attach-source) @ struts2-jquery ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- source:3.3.1:jar-no-fork (attach-sources) @ struts2-jquery ---
[INFO] 
[INFO] --- install:3.1.2:install (default-install) @ struts2-jquery ---
[INFO] Installing /Users/speters/workspace/struts2-jquery/pom.xml to /Users/speters/.m2/repository/com/jgeppert/struts2/jquery/struts2-jquery/5.1.0-SNAPSHOT/struts2-jquery-5.1.0-SNAPSHOT.pom
[INFO] 
[INFO] --- deploy:3.1.3:deploy (default-deploy) @ struts2-jquery ---


<img width="1203" alt="image" src="https://github.com/user-attachments/assets/d6f9e25a-9713-4368-a74c-8bc39cc08edf">

2024-11-21 06:07 UTC, lukaszlenart commented
> <releaseProfiles>release</releaseProfiles>

Looks like that was it, thanks!

2024-11-21 06:31 UTC, sepe81 approved these changes

2024-11-21 06:41 UTC, merged